### ISSUE TITLE
Limit the blog post `title` length to 3 rows ~85 characters

### ISSUE THREAD

**Issue by monacodelisa** [AnguHashBlog/angular#41]
**Describe the solution you'd like**
- for longed blog post titles, limit the displayed title to ~85 characters so it fits in 3 rows 
- add `...` as an indication that the title is longer

what it look like now:
![image](https://github.com/AnguHashBlog/angular/assets/64324417/49894f27-a488-4682-bca3-dbcd18963a39)

what would be better:
![image](https://github.com/AnguHashBlog/angular/assets/64324417/bfa92c16-f88c-4763-939a-e3e4b02e0237)

**Comment by Jayanth-Parthsarathy** [comment]
Hey @monacodelisa. I would love to work on it. Can you please assign this to me?

**Comment by Jayanth-Parthsarathy** [comment]
Hey @monacodelisa. There is a build folder `dist` inside the angular folder. Is it intended or should I remove this via gitignore?

**Comment by monacodelisa** [comment]
@Jayanth-Parthsarathy the `dist` folder is of course there intentionally. Please understand that when you are assigned a specific issue only work related to that specific issue can be performed and included in the PR. If the PR includes changes outside the scope of the specific issue, even if it is valid work - the PR will be automatically rejected.

**Comment by Jayanth-Parthsarathy** [comment]
Hey, @monacodelisa . I have truncated the title to 85 characters. Please have a look and let me know if any more changes are to be made.
