### ISSUE TITLE
Feature: add responsiveness for the posts view

### ISSUE THREAD

**Issue by hossameldinfahmi** [AnguHashBlog/angular#85]
### Type of feature
- implement responsiveness for the posts view 

- responsiveness has not yet been covered
- there are no media queries throughout the entire app therefore if any new work is being done related to responsiveness this is a feature, since there is no correction of existing code or implementation

## Prerequisites
- when working on responsiveness we must consider the entire screen, which includes the header and the footer
- we can either work on the entire screen view in one issue, or if it is split into smaller issues - header and footer's responsiveness should be added first

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by copypasteov** [comment]
@hossameldinfahmi Thanks for the issue, our team will look into it as soon as possible! If you would like to work on this issue, please wait for us to decide if it's ready. The issue will be ready to work on once we remove the "needs triage" label.

To claim an issue that does not have the "needs triage" label, please leave a comment that says ".take". If you have any questions, please reach out to us on [Discord](https://discord.gg/SQCFCACz) or follow up on the issue itself.

For full info on how to contribute, please check out our [contributors guide](https://anguhashblog.com/contributing).

**Comment by monacodelisa** [comment]
@hossameldinfahmi thank you for taking the time to create an issue :) 
This is not a bug fix, not all issues are bug fixes, there are features & bug fixes. You can read more about the difference here - [contributing](https://anguhashblog.com/contributing)

I have made the adjustments
