### ISSUE TITLE
Add pagination or load more for blog posts in - `posts` & `series`

### ISSUE THREAD

**Issue by copypasteov** [AnguHashBlog/angular#9]
**Additional context**
Right now the existing blog query is retrieving the first 10 blog posts, this is the initial state to get things going.
A pagination needs to be implemented that when the user navigates to the next page a different query is used to retrieve the next 10 posts and the next and so on.

In the query this is done by specifying `after 10`  I believe.

**Comment by copypasteov** [comment]
@jhonacs2 you can continue anything related to the issues here, did you say that you want to work on it ?

**Comment by jhonacs2** [comment]
@copypasteov Yes, I'm ready to working on this issue

**Comment by copypasteov** [comment]
@jhonacs2 ok great I have assigned you 👍

**Comment by copypasteov** [comment]
@jhonacs2 please discuss the implementation you are thinking of going for:
- pagination 
- load more 
?

**Comment by jhonacs2** [comment]
@copypasteov  hasnode currently has the component of load more ,  I want to do the same and load10 more posts
![image](https://github.com/HashnodeNG/angular/assets/75391330/b58feded-b5f4-48df-b790-a5e3e2aaf3b1),
then scroll through the following posts as they load (infinity scroll) this with a directive.
What do you think?

**Comment by monacodelisa** [comment]
@jhonacs2 that sounds perfect to me 👍 , but please wait a little bit more since realized something - I will have to rename the GitHub Organization as a whole - to be on the safe side legally - I am not going to use `hashnode` since this is trademarked name,
will do it today and let you know when I am done so you can clone the repo

**Comment by monacodelisa** [comment]
@jhonacs2 ok it is all ready now for this repo- please make a new fork since name is changed and then you can work as normal :)
